Updated animation components in images
cerebro-iiitv/cerebro-web-2020 pull request #14
Opened 2020-02-08 18:40 UTC by MayankAjmeri

Added common animation and repositioned to the components around spaceship image and planet on homepage.

2020-02-10 04:57 UTC, pAditya198 approved these changes

2020-02-10 04:58 UTC, MayankAjmeri commented
http://cerebro2020.surge.sh/

2020-02-10 05:01 UTC, pAditya198 requested changes

2020-02-10 05:01 UTC, pAditya198 commented on src/Components/Home/PastGlimpse/PastGlimpse.scss
>          transform: translateX(240px);
modify code here for 1340 for all the images.

2020-02-15 20:00 UTC, rossoskull commented on src/Components/Home/About/About.jsx
> +import "../../../scss/abstracts/_animations.scss";
You don't need to import this

2020-02-16 17:20 UTC, rossoskull approved these changes

2020-02-16 17:23 UTC, merged