Sponsors and headers v1.0
cerebro-iiitv/cerebro-web-2020 pull request #2
Opened 2020-01-21 15:45 UTC by vrajparesh

2020-01-21 19:06 UTC, Monal5031 requested changes

2020-01-21 19:06 UTC, Monal5031 commented on src/Components/Footer/Footer.jsx
> +            <div className="Container">
Would be useful to have class names related to blocks

2020-01-21 19:06 UTC, Monal5031 commented on src/Components/Footer/Footer.scss
> +    color: #ffffff;
Should be in constants

2020-01-21 19:06 UTC, Monal5031 commented on src/Components/Footer/Footer.scss
> +    color: #ffffff;
same here

2020-01-21 19:06 UTC, Monal5031 commented on src/Components/Footer/Footer.scss
> +    color: #ffffff
same here

2020-01-21 19:06 UTC, Monal5031 commented on src/Components/Footer/Footer.scss
> +    color: #ffffff;
same here

2020-01-21 19:06 UTC, Monal5031 commented on src/Components/Footer/Footer.jsx
> +            <div className="hrContainer"><hr color="grey" /></div>
@rossoskull sure about camelCase class names?

2020-01-23 18:06 UTC, merged

2020-02-24 08:34 UTC, anshumanv commented
@Monal5031 ko ignore kyo kar rahe ho juniors 😈

2020-02-24 09:08 UTC, Monal5031 commented
@anshumanv Task kam ho gaye kya office ke?

2020-02-24 09:10 UTC, anshumanv commented
I no task, I tp 😛

2020-02-24 09:15 UTC, Monal5031 commented
@PiyushPawar17 Manager ko tag kar toh yaha :joy: Free ke paise de raha voh

2020-02-24 09:39 UTC, PiyushPawar17 commented
@Monal5031 Next mission - Get **25 kills** in **Guardian: Overpass**

2020-03-07 19:34 UTC, harshendrashah commented
Somebody missing UX here?