Updated components in about section
cerebro-iiitv/cerebro-web-2020 pull request #54
Opened 2020-02-25 15:44 UTC by MayankAjmeri

Made the planet float in about section and added components around it
![Screenshot (25)](https://user-images.githubusercontent.com/48920341/75263250-bb680200-5813-11ea-85a0-047985dacc7c.png)
![Screenshot (26)](https://user-images.githubusercontent.com/48920341/75263260-bd31c580-5813-11ea-96cc-9396e7af773d.png)

2020-02-25 15:47 UTC, MayankAjmeri commented
http://cerebro_temp.surge.sh/

2020-02-25 18:31 UTC, rossoskull requested changes
![image](https://user-images.githubusercontent.com/27884543/75275845-2244e580-582b-11ea-880a-a7d07ba6b2d7.png)
The rotating elements should be above the background

2020-02-26 03:38 UTC, MayankAjmeri commented
http://cerebro_temp.surge.sh/

2020-02-26 13:22 UTC, rossoskull approved these changes

2020-02-26 13:22 UTC, merged