Components Added
cerebro-iiitv/cerebro-web-2020 pull request #56
Opened 2020-02-26 14:58 UTC by prathmeshkhandelwal1

savory-bears.surge.sh

2020-02-26 15:13 UTC, prathmeshkhandelwal1 commented
New surge link is cerebro60.surge.sh

2020-02-26 16:26 UTC, thepushkarp requested changes
Add media queries for widths of  1080 and 400

2020-02-29 02:24 UTC, thepushkarp commented
Any further updates on this @prathmeshkhandelwal1 ?

2020-03-02 12:38 UTC, yashshah2820 commented
@prathmeshkhandelwal1 resolve the merge conflicts as soon as possible.

2020-03-04 14:28 UTC, samagragupta reviewed
Updated surge link?

2020-03-04 18:16 UTC, rossoskull requested changes

2020-03-04 18:16 UTC, rossoskull commented on src/Components/Home/Cover/Cover.scss
> +    width: 26vw;
Don't use `vw`, we want fixed size of image.

2020-03-04 18:16 UTC, rossoskull commented on src/Components/Home/Cover/Cover.scss
> +  width: 3.3vw;
Same here.

2020-03-04 18:16 UTC, rossoskull commented on src/Components/Home/Cover/Cover.scss
> +  top: -3.5vw;
Use `%` or `px` for positioning

2020-03-07 11:31 UTC, rossoskull approved these changes

2020-03-07 11:32 UTC, merged