Footer v1.1
cerebro-iiitv/cerebro-web-2020 pull request #9
Opened 2020-01-25 15:01 UTC by vrajparesh

Resized al footerl elements according to the given design

2020-01-26 10:42 UTC, rossoskull commented
Please deploy it to [surge](https://surge.sh/) and comment the link. Contact @pAditya198 for help

2020-01-29 18:45 UTC, vrajparesh commented
@rossoskull please review this.

link:  http://cerebro-footer.surge.sh/

2020-01-30 07:38 UTC, rossoskull requested changes

2020-01-30 07:38 UTC, rossoskull commented on package.json
> +    "surge": "^0.21.3"
Remove surge from local package, add it globally to your system by `npm i -g surge`

2020-01-30 07:38 UTC, rossoskull commented on src/Components/Footer/Footer.jsx
> +		// 		<div className="logo">
Remove comments

2020-01-30 07:38 UTC, rossoskull commented on src/Components/Footer/Footer.scss
> +    width: 1808px;
Don't use a fixed width

2020-01-30 07:38 UTC, rossoskull commented on src/Components/Footer/Footer.scss
> +//     padding: 48px 80px 16px 16px;
Comments

2020-02-02 13:58 UTC, vrajparesh commented
![WhatsApp Image 2020-02-02 at 17 41 29](https://user-images.githubusercontent.com/10117584/73609287-2bf37880-45f2-11ea-9142-94880b79d4c5.jpeg)
Portrait view
![WhatsApp Image 2020-02-02 at 17 41 29 (1)](https://user-images.githubusercontent.com/10117584/73609294-344bb380-45f2-11ea-859a-9b36e3ea6ba6.jpeg)
Landscape(Rotated) view

2020-02-08 12:22 UTC, pAditya198 commented
There are 6 commits so squash them into 1

2020-02-08 12:22 UTC, pAditya198 commented
@vrajparesh

2020-02-08 17:01 UTC, rossoskull approved these changes

2020-02-08 17:01 UTC, merged